[[redirects]]
  from = "https://jianger.netlify.com/*"
  to = "https://jianger.space/:splat"
  force = true

# A redirect rule with all the supported properties
[[redirects]]
  from = "/old-path"
  to = "/new-path"
